# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
cull:
  enabled: false
ingress:
  enabled: true
singleuser:
  allowPrivilegeEscalation: false
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: maxullrich/jupyter-army-education
    tag: latest
  # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
  # which performs further customization on startup.
  cmd: null
  storage:
    dynamic:
      storageClass: nfs-client
    capacity: 10Gi
  lifecycleHooks:
    postStart:
        exec:
          command:
            [
              "gitpuller",
              "https://github.com/UMD-SustainabilityCenter/training-course",
              "main",
              "files",
            ]
  #   preStop:
  #     exec:
  #       command: ["pkill", "jupyterhub-sing"]
        # jupyterhub-sing
        #[\\w-]*jupyter[\\w-]*
hub:
  config:
    Authenticator:
      enable_auth_state: true
      admin_users:
        - Max
    #   allowed_users:
    #     - Osama
    #     - Oliver
    #     - Ali
    # DummyAuthenticator:
    #   password: password
    GitHubOAuthenticator:
      client_id: 
      client_secret: 
      oauth_callback_url: http://192.168.1.36/hub/oauth_callback
      hostedDomain: 192.168.1.36
      allowed_organizations:
        - UMD-SustainabilityCenter 
      scope:
        - read:org
    JupyterHub:
      authenticator_class: github
      cookie_options:
        secure: false
      admin_access: true
      admin_users:
        - MaxU1301
        - mullrich
# proxy:
#   service:
#     loadBalancerIP: 192.168.1.36
#   https:
#     enabled: true
#     hosts:
#       - https://jupyter.tothemax.pro/
#     letsencrypt:
#       contactEmail: max@ullrichfamily.com
